[[main]]
none = "none"

[[main]]
name = "Peoples"
pageRef = "/peoples"
identifier = "kM5WB51oYk"
weight = 3

[[main]]
name = "About"
pageRef = "about"
identifier = "68kwAuGu1m"
weight = 5

[[main]]
name = "Projects"
pageRef = "projects/"
identifier = "dxb0VrntYu"
weight = 1

[[main]]
name = "Vacancies"
pageRef = "vacancies/"
identifier = "xfcsYMmIlR"
weight = 4

[[main]]
name = "Publications"
pageRef = "publications/"
identifier = "wy6playQl3"
weight = 2

[[footer]]
name = "School of Computer Science"
url = "https://cs.ucd.ie"
identifier = "ELWjnIAIMF"
weight = 9_999

[[footer]]
name = "University College Dublin"
url = "https://www.ucd.ie/"
identifier = "GW5ed0FJZu"
weight = 9_999
