[[main]]
none = "none"

[[main]]
name = "About"
pageRef = "about"
identifier = "68kwAuGu1m"
weight = 5

[[main]]
name = "Projects"
pageRef = "projects/"
identifier = "dxb0VrntYu"
weight = 1

[[main]]
name = "Vacancies"
pageRef = "vacancies/"
identifier = "xfcsYMmIlR"
weight = 4

[[main]]
name = "Publications"
pageRef = "/publications"
identifier = "92Q2PGy38u"
weight = 2

[[footer]]
name = "University College Dublin"
url = "https://www.ucd.ie/"
identifier = "GW5ed0FJZu"
weight = 1

[[footer]]
name = "School of Computer Science"
url = "https://www.ucd.ie/cs/"
identifier = "ddri31r0WR"
weight = 9_999
