[[main]]
name = "About SOC² Lab"
pageRef = "about"
identifier = "RVYpEEdF9E"
weight = 1

[[main]]
name = "Research areas"
url = "/about/research_areas/"
identifier = "ZMM5zI0Cpl"
weight = 2

[[main]]
name = "Team"
pageRef = "peoples"
identifier = "KmE9d9B7ln"
weight = 5

[[main]]
name = "Publications"
pageRef = "publications"
identifier = "rv5RmWhsjr"
weight = 3

[[main]]
name = "Resources"
pageRef = "resources"
identifier = "pMpSGoUct6"
weight = 4

[[main]]
name = "Join us"
pageRef = "vacancies"
identifier = "0yTb9jv0lO"
weight = 6

[[main]]
name = "Contact us"
url = "/about/contact"
identifier = "NlnMvv7B47"
weight = 7


[[footer]]
name = "University College Dublin"
url = "https://www.ucd.ie/"
identifier = "GW5ed0FJZu"
weight = 1

[[footer]]
name = "School of Computer Science"
url = "https://www.ucd.ie/cs/"
identifier = "ddri31r0WR"
weight = 2
